### ISSUE TITLE
What model splitting generated these data

### ISSUE THREAD

**Issue by cjmcgill** [ClapeyronThermo/spt-nrtl-db#1]
Hello, I'm interested in the provenance of the parameters in this repository as something I can use to generate comparative metrics for SPT-NRTL with. Are these data generated by a model 1) using all available VLE data for training, 2) in a cross-validation scheme so that all these are comparable to test data, or is it some other model splitting state? I can't tell from the readme or the original paper. Thanks!

**Comment by pw0908** [comment]
Hi Chas!

I'll first mention that we are not the authors of SPT-NRTL. This is just a database that could be used in our other package Clapeyron.

That being said, you can see in section 2.2 of their original article (https://doi.org/10.1016/j.fluid.2023.113731), they used a combination of synthetic data for pre-training and experimental data for fine-tuning. For the fine-tuning, they did have three validation sets, testing the extrapolation capabilities of the model.

Let us know if you have any further questions!

**Comment by cjmcgill** [comment]
Hi Pierre! I thought you may be associated because the link to results from the original paper no longer works, so this github may be the only place to find them anymore.

They mention this drop of data in the end of section 3.3. From the way that they talk about it, I best understand it as implying that it's from a retraining using the whole dataset as the training set before these predictions rather than one of their validation treatments, but it's not unambiguous.

**Comment by cjmcgill** [comment]
I've now found the answer in the SI entry. It's from a full data retraining.
"An SPT-NRTL model trained on the full available dataset is used to calculate the NRTL parameters of all combinations of 10 000 molecules, yielding a total of 100 000 000 sets of NRTL parameters."
